# SciPy Tutorial - Presented by PyPower

## Scipy Intoduction

### SciPy = Scientific Python

SciPy is a collection of mathematical algorithms and convenience functions built on the Numpy extension of Python. It with high-level commands and classes for manipulating and visualizing data. 

The additional benefit of basing SciPy on Python is that this also makes a powerful programming language available for use in developing sophisticated programs and specialized applications. 

Let's start with the contents of tutorial.

## Contents Covered :

#### 1) Basic -  Polynomial
#### 2) Special Funtion 
#### 3) Integration
#### 4) Linear Algebra 
#### 5) Fourier Transformation 
#### 6) Statistics

## 1) Basic - Polynomial

In [1]:
from numpy import poly1d
p = poly1d([3,6,8])
print(p)

   2
3 x + 6 x + 8


In [2]:
print(p*p)  #(3x^2 + 4^x + 5)^2

   4      3      2
9 x + 36 x + 84 x + 96 x + 64


In [3]:
print(p)
print(" p(2) = ",p(2))
print(" p(2) and p(3) = ",p([2,3]))

   2
3 x + 6 x + 8
 p(2) =  32
 p(2) and p(3) =  [32 53]


In [4]:
#Roots of p
p.r

array([-1.+1.29099445j, -1.-1.29099445j])

In [5]:
#coefficients of p
p 

poly1d([3, 6, 8])

In [6]:
print(p)
p1 = poly1d([1,2,3],variable='y') #equation with variable as y
print()
print(p1)

   2
3 x + 6 x + 8

   2
1 y + 2 y + 3


In [7]:
#Integration of a Polynomial

print(p.integ(k=6)) #k = indefinite integration constant

   3     2
1 x + 3 x + 8 x + 6


In [8]:
# Differentiation of a Polynomial

print(p.deriv())

 
6 x + 6


## 2) Special Function (import scipy.special)

In [9]:
import scipy.special

In [10]:
import numpy as np
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
#Cube Root
scipy.special.cbrt(a)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382, 2.15443469])

In [12]:
# Exponent of 10 (exp10())
x = 3
scipy.special.exp10(x)

1000.0

In [13]:
# Exponent of 2 (exp2())
x = 3
scipy.special.exp2(x)

8.0

In [14]:
# Degree to Radian (radian(d,m,s))
d = 30
m = 10
s = 50
scipy.special.radian(d,m,s)

0.5267500645255109

In [15]:
# Trigonometric Funtions (in degrees)
print("Sine of 30 degrees = ",scipy.special.sindg(30))
print("Cosine of 30 degrees = ",scipy.special.cosdg(30))
print("Tangent of 30 degrees = ",scipy.special.tandg(30))


Sine of 30 degrees =  0.49999999999999994
Cosine of 30 degrees =  0.8660254037844387
Tangent of 30 degrees =  0.5773502691896257


In [16]:
# Permutation
scipy.special.perm(5,2) #5P2 = 20

20.0

In [17]:
# Combination
scipy.special.comb(5,2) #5C2 = 10

10.0

## 3) Integration (import scipy.integrate)

### Numerous Types of Integration are available in scipy

   1. quad - Single integration 
   2. dblquad - Double integration 
   3. tplquad - Triple integration 
   4. nquad  - n-fold multiple integration
   5. and many more...

In [18]:
import scipy.integrate

#### Lambda Function in brief

In [19]:
f = lambda x : x**2
f(3)

9

In [20]:
g = lambda x,y : x*y
g(2,3)

6

In [21]:
h = lambda x,y : x**2 + 2*x*y + y**2 #(x+y)^2
h(1,2)  #(1+2)^2

9

In [22]:
# scipy.integrate.quad(func, lower_limit, upper_limit)

In [23]:
f = lambda x : x**3
i = scipy.integrate.quad(f, 1, 2)
i

(3.7500000000000004, 4.1633363423443377e-14)

In [24]:
from numpy import exp
f= lambda x:exp(-x**3)
i = scipy.integrate.quad(f, 1, 4)
i

(0.08546832942957776, 2.1640276156712023e-12)

In [25]:
# Double Integration (Used for area under curve)

#scipy.integrate.dblquad(func, lower_limit, upper_limit, func2, func3)
area = scipy.integrate.dblquad(lambda x, y: x*y, 0, 0.5, lambda x: 0, lambda y: 1-2*y)
area

(0.010416666666666668, 4.101620128472366e-16)

## 4) Linear Algebra (import scipy.linalg)

In [26]:
from scipy import linalg

In [27]:
import numpy as np

In [28]:
a1 = np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [29]:
# Determinant of a matrix
linalg.det(a1)

-2.0

Compute pivoted LU decomposition of a matrix.

The decomposition is::

    A = P L U

where P is a permutation matrix, L lower triangular with unit
diagonal elements, and U upper triangular.

In [30]:
A = np.array([[1,2,3],[4,5,6],[7,8,8]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [31]:
P, L, U = linalg.lu(A)

In [32]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [33]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [34]:
U

array([[7.        , 8.        , 8.        ],
       [0.        , 0.85714286, 1.85714286],
       [0.        , 0.        , 0.5       ]])

We can find out the eigenvector and eigenvalues of a matrix:

In [35]:
EV, EW = linalg.eig(A)

In [36]:
#Eigen Values
EV

array([15.55528261+0.j, -1.41940876+0.j, -0.13587385+0.j])

In [37]:
#Eigen Vectors
EW

array([[-0.24043423, -0.67468642,  0.51853459],
       [-0.54694322, -0.23391616, -0.78895962],
       [-0.80190056,  0.70005819,  0.32964312]])

Solving systems of linear equations can also be done:

In [38]:
B = np.array([[2],[3],[5]])
B

array([[2],
       [3],
       [5]])

In [39]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [40]:
#Solve Linear Equation using Matrix (AX=B)
#linalg.solve()

X = linalg.solve(A,B)


In [41]:
X    #Solution : (7/3, 11/3, 1)

array([[-2.33333333],
       [ 3.66666667],
       [-1.        ]])

#### Inverse of a matrix

In [42]:
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [43]:
#Inverse : linalg.inv()

linalg.inv(A)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

In [44]:
#Cross Check
# A * inv(A) = I

I = A.dot(linalg.inv(A))
print(np.around(I))

[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]


## 5) Fourier Transformation (import scipy.fftpack)

#### What is Fourier Transformation
The Fourier Transform is a tool that breaks a waveform (a function or signal) into an alternate representation, characterized by sine and cosines. The Fourier Transform shows that any waveform can be re-written as the sum of sinusoidal functions.

There are two major functions of fftpack :
- fft : fast fourier transformation
- ifft : inverse fast fourier transformation

In [45]:
import scipy.fftpack

In [46]:
import numpy as np
a = np.array([1,5,6,14,25,40])
a

array([ 1,  5,  6, 14, 25, 40])

In [47]:
# Fourier Transform
y = scipy.fftpack.fft(a)
y

array([ 91. -0.j        ,  -6.+46.7653718j , -23.+13.85640646j,
       -27. -0.j        , -23.-13.85640646j,  -6.-46.7653718j ])

In [48]:
# Inverse Fourier Transform
invy = scipy.fftpack.ifft(a)
invy

array([15.16666667-0.j        , -1.        -7.79422863j,
       -3.83333333-2.30940108j, -4.5       -0.j        ,
       -3.83333333+2.30940108j, -1.        +7.79422863j])

In [49]:
# Cross Verification
i = scipy.fftpack.fft(invy)
print(i)
print()
print(a)

[ 1.+0.j  5.+0.j  6.-0.j 14.+0.j 25.+0.j 40.+0.j]

[ 1  5  6 14 25 40]


## 6) Statistics (import scipy.stats)

### Common Methods

The main public methods for continuous RVs are:

- rvs: Random Variates
- pdf: Probability Density Function
- cdf: Cumulative Distribution Function
- sf: Survival Function (1-CDF)
- ppf: Percent Point Function (Inverse of CDF)
- isf: Inverse Survival Function (Inverse of SF)
- stats: Return mean, variance, (Fisher’s) skew, or (Fisher’s) kurtosis
- moment: non-central moments of the distribution

Let’s take a normal RV as an example. 

### Probability Distributions

In [50]:
from scipy.stats import norm

In [51]:
#this gives you a numpy array with 500 elements, 
#randomly valued according to the standard normal distribution (mean = 0, std =1)
x_norm = norm.rvs(size = 500)
print(type(x_norm))

<class 'numpy.ndarray'>


In [52]:
norm.mean(), norm.std(), norm.var() #Mean = 0, std = 1

(0.0, 1.0, 1.0)

In [53]:
#CDF
import numpy as np
norm.cdf(np.array([1,-1., 0, 1, 3, 4, -2, 6])) #Continous Distribution Function

array([0.84134475, 0.15865525, 0.5       , 0.84134475, 0.9986501 ,
       0.99996833, 0.02275013, 1.        ])

In [54]:
#PPF
# It is reverse of CDF
norm.ppf(0.5)   #Percent Point Function

0.0

In [55]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x.max(),x.min(),x.mean(),x.var(),sep=",")

9,1,5.0,6.666666666666667


In [56]:
#Geometric Mean
from scipy.stats.mstats import gmean 
g = gmean([1, 5, 20]) 

print("Geometric Mean is :", g) 


Geometric Mean is : 4.641588833612778


In [57]:
#Harmonic Mean
from scipy.stats.mstats import hmean 
h = hmean([1, 5, 20]) 

print("Harmonic Mean is :", h)

Harmonic Mean is : 2.4


In [58]:
#Mode 
from scipy import stats
arr1 = np.array([1, 3, 15, 11, 9, 3]) 
print("Arithmetic mode is : ", stats.mode(arr1)) 


Arithmetic mode is :  ModeResult(mode=array([3]), count=array([2]))


In [59]:
#Z-Score	
arr1 = [20, 2, 7, 1, 25] 

print ("\nZ-score for arr1 : ", stats.zscore(arr1)) 



Z-score for arr1 :  [ 0.92435403 -0.92435403 -0.41082402 -1.02706004  1.43788405]
