In [9]:
p=[1,2,3,4]
p

[1, 2, 3, 4]

In [10]:
import numpy as  np

# The Basic

In [11]:
d=np.array(p)
d

array([1, 2, 3, 4])

In [12]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [13]:
b=np.array([[1.0,2.0,3.0],[3.0,4.0,5.0]])
print(b)

[[1. 2. 3.]
 [3. 4. 5.]]


# Get Demension

In [14]:
b.ndim

2

# Get Shape

In [15]:
b.shape

(2, 3)

# Get  Type

In [16]:
a.dtype

dtype('int32')

# Declaring array with data type

In [17]:
d=np.array([1,2,3],dtype='int32')
print(d)

[1 2 3]


In [18]:
d.dtype

dtype('int32')

# Get Size

In [19]:
d.itemsize

4

# Total size

In [20]:
a.nbytes

12

# Accessing specific elements,rows,colums,etc

In [21]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [22]:
a.shape

(2, 7)

# Specific element-->[r,c]

In [23]:
a[1,5]

13

# Get specific row

In [24]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

# Get specific column

In [25]:
a[:,2]

array([ 3, 10])

# Range

In [38]:
a=np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

# Comparision

In [40]:
a>5


array([False, False, False, False, False])

In [42]:
a<6

array([ True,  True,  True, False, False])

In [45]:
a==6

True

# Change from and array

In [20]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [21]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


# 3d example
        

In [30]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Get speficic element in 3d array

In [31]:
b[0,1,1]

4

In [32]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

# Replace 

In [34]:
b[:,1,:]=[[9,8],[10,11]]

In [35]:
b

array([[[ 1,  2],
        [ 9,  8]],

       [[ 5,  6],
        [10, 11]]])

# Initalizing different types of array


# Null Martix

In [39]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# Ones Martix

In [41]:
np.ones((2,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

# Any onther number

In [42]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

# Any other number(full-like)

In [7]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [8]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

# Random decimal number

In [11]:
np.random.rand(4,2)

array([[0.90527225, 0.65380331],
       [0.10101957, 0.31524323],
       [0.51047809, 0.47628589],
       [0.85181949, 0.81431823]])

In [12]:
np.random.random_sample(a.shape)

array([[0.50356214, 0.68411733, 0.45266371, 0.88462309, 0.15631139,
        0.84066177, 0.73366604],
       [0.14480407, 0.19177067, 0.56967747, 0.97957664, 0.01708319,
        0.28195559, 0.77883243]])

# Random integer number

In [14]:
np.random.randint(4,7,size=(3,3))

array([[4, 6, 4],
       [4, 6, 4],
       [4, 5, 5]])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Repeat an array

In [21]:
arr=np.array([[1,2,3]])
n1=np.repeat(arr,3,axis=0)
print(n1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [27]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be Carefull of copying arrays

In [35]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Maths

In [39]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [40]:
a+2

array([3, 4, 5, 6])

In [41]:
a-2

array([-1,  0,  1,  2])

In [42]:
a*2

array([2, 4, 6, 8])

In [43]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [45]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [46]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

# Take sin of all value

In [47]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [46]:
np.sqrt(a)

2.449489742783178

In [47]:
np.log(a)

1.791759469228055

# Linear algebra

In [55]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

# Find the determinit

In [54]:
c=np.identity(3)
np.linalg.det(c)

1.0

# Link https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

# statistics

In [51]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:

np.min(stats)

1

In [53]:
np.max(stats, axis=1)

array([3, 6])

In [54]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [56]:
np.mean(stats,axis=1)

array([2., 5.])